"""users table

Revision ID: 63abc948f0fb
Revises: 
Create Date: 2019-12-09 13:00:01.710111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63abc948f0fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinamica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medidas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperatura', sa.Float(), nullable=False),
    sa.Column('UR', sa.Float(), nullable=False),
    sa.Column('reator_CO2_1', sa.Integer(), nullable=False),
    sa.Column('reator_CO2_2', sa.Integer(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reator_fermentacao_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co2', sa.Integer(), nullable=False),
    sa.Column('data_excel', sa.Float(), nullable=False),
    sa.Column('art_estimado', sa.Float(), nullable=False),
    sa.Column('etanol_estimado', sa.Float(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reator_fermentacao_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('co2', sa.Integer(), nullable=False),
    sa.Column('data_excel', sa.Float(), nullable=False),
    sa.Column('art_estimado', sa.Float(), nullable=False),
    sa.Column('etanol_estimado', sa.Float(), nullable=False),
    sa.Column('data_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reator_fermentacao_2')
    op.drop_table('reator_fermentacao_1')
    op.drop_table('medidas')
    op.drop_table('dinamica')
    # ### end Alembic commands ###
